### PR TITLE
adding the possibility of using NPM and RequireJS

### PR DESCRIPTION
**Pull request by raulmangolin**
I added a few lines in package.json for anyone who want to use the jcarouselSwipe with RequireJS can use without problems.

Also added a few lines in README.md with sample use.

If you are ok with this, add the package on www.npmjs.com :)

### CODE REVIEW

**Comment by snake-345** [comment]
Thanks man.

**Comment by snake-345** [comment]
I can't add this package to npm, because you already done it)

**Comment by raulmangolin** [comment]
Oops, sorry.

It's a test. I'll remove it.

**Comment by raulmangolin** [comment]
I added you as a collaborator. You can remove me.

**Comment by snake-345** [comment]
Thanks for your help)

**Pull request merged**
